Use Locale.US for Android
auth0/auth0-flutter pull request #238
Opened 2023-04-11 15:55 UTC by Mecharyry

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

Offering as an alternative to https://github.com/auth0/auth0-flutter/pull/206 which aligns how Android and iOS parse dates. iOS is already formatting dates to `ISO8601String` by directly taking the `expiresAt` property, without modification. Android on the other hand is modifying this `expiresAt` by allowing it to be localised to whatever the systems `getDefaultLocale` is. 

To solve the issues we have seen with `ar` this ensures that all dates are using a consistent Locale of `Locale.US`. The test added `credentials_test` is used just to illustrate the breaking change, but is actually fixed at the native level.

### 📎 References

No references.

### 🎯 Testing

Put your device into `Arabic` and attempt to use this library to log in. You'll notice that it works in this MR but doesn't on `main`

2023-04-14 13:52 UTC, Mecharyry commented
> Thankss @Mecharyry - can you elaborate on the breaking change? Does it introduce one?

Sorry I goofed when writing the description. I meant to write that the test class illustrates why parsing an Arabic specific date time breaks vs a US one. I've updated the description.

2023-05-02 06:44 UTC, poovamraj commented
@stevehobbsdev I'd prefer this solution as well over the other. LGTM 👍

2023-05-03 15:03 UTC, poovamraj requested changes

2023-05-03 15:03 UTC, poovamraj commented on auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
> +                    SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ", Locale.US)
Can we use the format `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` as that is the one used in Android and iOS.

2023-05-03 15:03 UTC, poovamraj commented on auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithOtpApiRequestHandler.kt
> +                    SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ", Locale.US)
Same as above for all the format strings

2023-05-12 15:46 UTC, Mecharyry commented
@poovamraj Sorry for the delay, I've made the requested changes!

2023-05-18 08:02 UTC, Mecharyry commented
@poovamraj @stevehobbsdev Can I get some eyes on this? It would be great to merge this so I can stop maintaining a fork 😄

2023-05-23 09:44 UTC, stevehobbsdev commented
@Mecharyry Thanks for your patience here. We're gearing up for a new release that includes web support, this PR will be included along with that work. We're aiming for that release within the next week or so.

2023-05-25 10:19 UTC, stevehobbsdev approved these changes

2023-05-25 10:34 UTC, poovamraj approved these changes
Checked the repo for use of Locale.getDefault(). Looks fine to me +1

2023-05-25 11:10 UTC, merged