Use java.time.Instant instead of java.text.SimpleDateFormat
auth0/auth0-flutter pull request #469
Opened 2024-07-23 07:54 UTC by gferon

### 📋 Changes

This is a proposed alternative to #468 which simplifies the approach and avoids future mistakes since `java.time.Instant` works with time-unaware and only parses and produces ISO-8601 formatted strings.

### 🎯 Testing

Making sure the tests still use `SimpleDateFormat` is a great way to avoid having the actual implementation have the same bug than the tests. Unit tests should be good enough in that case.

2024-09-09 11:53 UTC, gferon commented
Could anybody in the team review #469 or #468 depending on the preferred change? We're running a patched version of `auth0_flutter` and I would be happy if this fix could be merged.

2024-09-09 12:13 UTC, pmathew92 requested changes
Please remove all println statements from the codebase

2024-09-09 12:14 UTC, pmathew92 commented
@gferon  Thank you for raising this PR . the team will have a look into this

2024-09-09 12:45 UTC, gferon commented
> Please remove all println statements from the codebase

Sure, I mostly wanted to first know which approach you favor.

2024-09-16 12:43 UTC, desusai7 reviewed
Hi @gferon

Thank you for raising the PR, I've reviewed it and it looks good to me, Can you remove the println statements and also update the tests accordingly ?

2024-09-19 14:57 UTC, desusai7 commented
@gferon, thanks a lot for addressing the comment, can you please update the unit tests as well to use `java.time.Instant` ?

2024-09-19 16:01 UTC, gferon commented
> @gferon, thanks a lot for addressing the comment, can you please update the unit tests as well to use `java.time.Instant` ?

I updated the PR description. I think it's actually good to keep the old way of doing it in the tests, to avoid testing a bug itself (which was happening before).

2024-10-01 13:14 UTC, gferon commented
Hi @pmathew92 could you maybe at least approve the workflow runs so I can fix any CI issues before we move forward? The bug is still out there and it's not a nice one.

2024-10-01 16:07 UTC, pmathew92 commented
@gferon  Apologies . I have approved the workflow runs. Looks like the merge is blocked due to not being signed commits.Could you please sign your commits

2024-10-08 20:08 UTC, tikal commented
Hi, any update on this?

2024-10-08 20:27 UTC, gferon commented
> Could you please sign your commits

@pmathew92 I have signed my commits, not sure why it's a requirement in the first place.

2024-10-09 06:56 UTC, merged

2024-10-09 06:57 UTC, pmathew92 commented
@gferon  We have merged the PR . Thank you for your contributions