feat(auth): 🔐 Add UserProfile serialization and include in Credentials
auth0/auth0-flutter pull request #475
Opened 2024-09-19 04:47 UTC by Rohithgilla12

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

- Add userProfile to Credentials.toMap() method
- Implement toMap() method in UserProfile class
- Update existing tests and add new UserProfile tests

### 🎯 Testing

Added tests for the updated code and all of the tests pass
![image](https://github.com/user-attachments/assets/3b4c07c3-38a9-48f5-a021-21ee8d4d416b)

2025-02-10 19:25 UTC, Widcket commented on auth0_flutter_platform_interface/test/user_profile_test.dart
> +      expect(userProfile.isEmailVerified, isNull);
```suggestion
      };

      final userProfile = UserProfile.fromMap(map);

      expect(userProfile.sub, 'user123');
      expect(userProfile.email, 'john@example.com');
      expect(userProfile.name, isNull);
      expect(userProfile.givenName, isNull);
      expect(userProfile.familyName, isNull);
      expect(userProfile.middleName, isNull);
      expect(userProfile.nickname, isNull);
      expect(userProfile.preferredUsername, isNull);
      expect(userProfile.profileUrl, isNull);
      expect(userProfile.pictureUrl, isNull);
      expect(userProfile.websiteUrl, isNull);
      expect(userProfile.email, isNull);
      expect(userProfile.isEmailVerified, isNull);
```
The only required property is `sub`.

2025-02-10 19:26 UTC, Widcket commented on auth0_flutter_platform_interface/test/user_profile_test.dart
> +      };
```suggestion
      final map = {'sub': 'user123'};
```
`email` is not required.

2025-02-10 19:27 UTC, Widcket commented on auth0_flutter_platform_interface/test/user_profile_test.dart
> +      expect(userProfile.isEmailVerified, isNull);
```suggestion
      expect(userProfile.websiteUrl, isNull);
      expect(userProfile.email, isNull);
      expect(userProfile.isEmailVerified, isNull);
```
`email` is not required.

2025-02-10 19:30 UTC, Widcket commented on auth0_flutter_platform_interface/test/user_profile_test.dart
> +      expect(userProfile.email, 'john@example.com');
```suggestion
```
Putting `email` below.

2025-02-10 19:33 UTC, Widcket commented
Hi @Rohithgilla12, thanks for your contribution. We really appreciate it; it's carefully done. In order to merge it, we'd need the commits to be verified.

2025-02-10 19:33 UTC, Widcket approved these changes

2025-02-10 22:08 UTC, Widcket requested changes
My bad, just saw that one if the Dart tests is failing: https://github.com/auth0/auth0-flutter/actions/runs/13248920908/job/36989584252?pr=475

2025-04-07 11:25 UTC, pmathew92 commented
@Rohithgilla12  Could you fix the failing test in the auth0_flutter_platform_interface ?

2025-04-07 11:46 UTC, Rohithgilla12 commented
@pmathew92 Hey should be good to do I think!

2025-04-09 22:34 UTC, Widcket commented
Hi @Rohithgilla12, could you please make sure the commits are signed? That's the only thing preventing the merge.

<img width="389" alt="Screenshot 2025-04-09 at 23 34 16" src="https://github.com/user-attachments/assets/74277966-df5f-493a-8e85-67fd38115a8a" />

2025-04-10 02:43 UTC, closed without merging